language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_scripts:
  - echo "no tests"

script:
  - docker --version # print the version of docker for logging
  - docker build -t udagram-microservice-feed .
  - docker tag udagram-microservice-feed simonotter/udagram-microservice-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push simonotter/udagram-microservice-feed